"""urls file."""

from django.conf.urls.defaults import *
from geodata import views

urlpatterns = patterns('',
    url(r'^all/patrimony/$', views.show_patrimony_all,
        name = "show_patrimony_all"),
    url(r'^all/construction/$', views.show_construction_all,
        name = "show_construction_all"),
    url(r'^all/meeting/$', views.show_meeting_all,
        name = "show_meeting_all"),
    url(r'^patrimony/(?P<ident>\d+)/$', views.show_patrimony,
        name = "show_patrimony"),
    url(r'^construction/(?P<ident>\d+)/$', views.show_construction,
        name = "show_construction"),
    url(r'^meeting/(?P<ident>\d+)/$', views.show_meeting,
        name = "show_meeting"),
    url(r'^edit/patrimony/(?P<ident>\d+)/$', views.edit_patrimony,
        name = "edit_patrimony"),
    url(r'^edit/construction/(?P<ident>\d+)/$', views.edit_construction,
        name = "edit_construction"),
    url(r'^edit/meeting/(?P<ident>\d+)/$', views.edit_meeting,
        name = "edit_meeting"),
    url(r'^delete/patrimony/(?P<ident>\d+)/$', views.delete_patrimony,
        name = "delete_patrimony"),
    url(r'^delete/construction/(?P<ident>\d+)/$', views.delete_construction,
        name = "delete_construction"),
    url(r'^delete/meeting/(?P<ident>\d+)/$', views.delete_meeting,
        name = "delete_meeting"),
    url(r'^add/patrimony/$', views.add_patrimony, name = "add_patrimony"),
    url(r'^add/construction/$', views.add_construction,
        name = "add_construction"),
    url(r'^add/meeting/$', views.add_meeting, name = "add_meeting"),
    url(r'^rec/patrimony/(?P<ident>\d+)/$', views.toggle_rec_patrimony,
        name = "toggle_rec_patrimony"),
    url(r'^rec/construction/(?P<ident>\d+)/$', views.toggle_rec_construction,
        name = "toggle_rec_construction"),
    url(r'^rec/meeting/(?P<ident>\d+)/$', views.toggle_rec_meeting,
        name = "toggle_rec_meeting"),
    url(r'^map/$', views.show_bigmap,
        name = "show_bigmap"),
)
