"""urls file."""

from django.conf.urls.defaults import *
from geodata import views

urlpatterns = patterns('',
    url(r'^patrimony/all/$', views.show_patrimony_all,
        name = "show_patrimony_all"),
    url(r'^patrimony/contemporary/$', views.show_patrimony_contemporary,
        name = "show_patrimony_contemporary"),
    url(r'^patrimony/unesco/$', views.show_patrimony_unesco,
        name = "show_patrimony_unesco"),
    url(r'^patrimony/vernacular/$', views.show_patrimony_vernacular,
        name = "show_patrimony_vernacular"),
    url(r'^patrimony/normal/$', views.show_patrimony_normal,
        name = "show_patrimony_normal"),
    url(r'^patrimony/(?P<ident>\d+)/$', views.show_patrimony,
        name = "show_patrimony"),
    url(r'^construction/participative/$', views.show_construction_participative,
        name = "show_construction_participative"),
    url(r'^construction/normal/$', views.show_construction_normal,
        name = "show_construction_normal"),
    url(r'^construction/all/$', views.show_construction_all,
        name = "show_construction_all"),
    url(r'^construction/(?P<ident>\d+)/$', views.show_construction,
        name = "show_construction"),
    url(r'^meeting/all/$', views.show_meeting_all,
        name = "show_meeting_all"),
    url(r'^meeting/(?P<ident>\d+)/$', views.show_meeting,
        name = "show_meeting"),
    url(r'^patrimony/(?P<ident>\d+)/edit/$', views.edit_patrimony,
        name = "edit_patrimony"),
    url(r'^construction/(?P<ident>\d+)/edit/$', views.edit_construction,
        name = "edit_construction"),
    url(r'^meeting/(?P<ident>\d+)/edit/$', views.edit_meeting,
        name = "edit_meeting"),
    url(r'^patrimony/(?P<ident>\d+)/delete/$', views.delete_patrimony,
        name = "delete_patrimony"),
    url(r'^construction/(?P<ident>\d+)/delete/$', views.delete_construction,
        name = "delete_construction"),
    url(r'^meeting/(?P<ident>\d+)/delete/$', views.delete_meeting,
        name = "delete_meeting"),
    url(r'^patrimony/add/$', views.add_patrimony, name = "add_patrimony"),
    url(r'^construction/add/$', views.add_construction,
        name = "add_construction"),
    url(r'^meeting/add/$', views.add_meeting, name = "add_meeting"),
    url(r'^patrimony/(?P<ident>\d+)/rec/$', views.toggle_rec_patrimony,
        name = "toggle_rec_patrimony"),
    url(r'^construction/(?P<ident>\d+)/rec/$', views.toggle_rec_construction,
        name = "toggle_rec_construction"),
    url(r'^meeting/(?P<ident>\d+)/rec/$', views.toggle_rec_meeting,
        name = "toggle_rec_meeting"),
    url(r'^all/$', views.show_bigmap,
        name = "show_bigmap"),
)
