"""urls file."""

from django.conf.urls.defaults import *
from geodata import views
from geodata import feeds

urlpatterns = patterns('',
    url(r'^feeds/patrimony/$', feeds.PatrimonyFeed(), name = "feed_patrimony"),
    url(r'^feeds/construction/$', feeds.ConstructionFeed(), name = "feed_construction"),
    url(r'^feeds/meeting/$', feeds.MeetingFeed(), name = "feed_meeting"),
    url(r'^feeds/actor/$', feeds.ActorFeed(), name = "feed_actor"),
    url(r'^patrimony/all/$', views.PatrimonyAllView.as_view(),
        name = "show_patrimony_all"),
    url(r'^patrimony/contemporary/$', views.PatrimonyContemporaryView.as_view(),
        name = "show_patrimony_contemporary"),
    url(r'^patrimony/unesco/$', views.PatrimonyUnescoView.as_view(),
        name = "show_patrimony_unesco"),
    url(r'^patrimony/vernacular/$', views.PatrimonyVernacularView.as_view(),
        name = "show_patrimony_vernacular"),
    url(r'^patrimony/normal/$', views.PatrimonyNormalView.as_view(),
        name = "show_patrimony_normal"),
    url(r'^patrimony/(?P<ident>\d+)/$', views.show_patrimony,
        name = "show_patrimony"),
    url(r'^construction/all/$', views.ConstructionAllView.as_view(),
        name = "show_construction_all"),
    url(r'^construction/participative/$', views.ConstructionParticipativeView.as_view(),
        name = "show_construction_participative"),
    url(r'^construction/normal/$', views.ConstructionNormalView.as_view(),
        name = "show_construction_normal"),
    url(r'^construction/(?P<ident>\d+)/$', views.show_construction,
        name = "show_construction"),
    url(r'^meeting/all/$', views.MeetingAllView.as_view(),
        name = "show_meeting_all"),
    url(r'^meeting/seminar/$', views.MeetingSeminarView.as_view(),
        name = "show_meeting_seminar"),
    url(r'^meeting/colloquium/$', views.MeetingColloquiumView.as_view(),
        name = "show_meeting_colloquium"),
    url(r'^meeting/conference/$', views.MeetingConferenceView.as_view(),
        name = "show_meeting_conference"),
    url(r'^meeting/festival/$', views.MeetingFestivalView.as_view(),
        name = "show_meeting_festival"),
    url(r'^meeting/(?P<ident>\d+)/$', views.show_meeting,
        name = "show_meeting"),
    url(r'^actor/all/$', views.ActorAllView.as_view(),
        name = "show_actor_all"),
    url(r'^actor/(?P<ident>\d+)/$', views.show_actor,
        name = "show_actor"),
    url(r'^patrimony/(?P<ident>\d+)/edit/$', views.edit_patrimony,
        name = "edit_patrimony"),
    url(r'^construction/(?P<ident>\d+)/edit/$', views.edit_construction,
        name = "edit_construction"),
    url(r'^meeting/(?P<ident>\d+)/edit/$', views.edit_meeting,
        name = "edit_meeting"),
    url(r'^actor/(?P<ident>\d+)/edit/$', views.edit_actor,
        name = "edit_actor"),
    url(r'^patrimony/(?P<ident>\d+)/delete/$', views.delete_patrimony,
        name = "delete_patrimony"),
    url(r'^construction/(?P<ident>\d+)/delete/$', views.delete_construction,
        name = "delete_construction"),
    url(r'^meeting/(?P<ident>\d+)/delete/$', views.delete_meeting,
        name = "delete_meeting"),
    url(r'^actor/(?P<ident>\d+)/delete/$', views.delete_actor,
        name = "delete_actor"),
    url(r'^patrimony/add/$', views.add_patrimony, name = "add_patrimony"),
    url(r'^construction/add/$', views.add_construction,
        name = "add_construction"),
    url(r'^meeting/add/$', views.add_meeting, name = "add_meeting"),
    url(r'^actor/add/$', views.add_actor, name = "add_actor"),
    url(r'^patrimony/(?P<ident>\d+)/rec/$', views.toggle_rec_patrimony,
        name = "toggle_rec_patrimony"),
    url(r'^construction/(?P<ident>\d+)/rec/$', views.toggle_rec_construction,
        name = "toggle_rec_construction"),
    url(r'^meeting/(?P<ident>\d+)/rec/$', views.toggle_rec_meeting,
        name = "toggle_rec_meeting"),
    url(r'^actor/(?P<ident>\d+)/rec/$', views.toggle_rec_actor,
        name = "toggle_rec_actor"),
    url(r'^all/$', views.BigMapView.as_view(),
        name = "show_bigmap"),
)
